theme: jekyll-theme-Cayman
title: "Oliver's Blog"
description: "A blog about programming, technology, and life."
author:
  name: "Oliver"
  email: "OliverzhtJackson@gmail.com"
baseurl: ""
url: "https://oliverzht.github.io"
