theme: jekyll-theme-cayman
title: Oliver Jackson | Software Developer
description: Personal website showcasing my projects and technical blog
url: "https://oliverjacksonzht.github.io"
show_downloads: false
google_analytics: UA-XXXXXXXXX-X  # 替换成你的Google Analytics ID

# 自定义样式
override_theme_styles: true

# 社交链接
social_links:
  github: oliverjacksonZht
  email: oliverzhtjackson@gmail.com        # 替换成你的真实邮箱

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 扩展导航
defaults:
  - scope:
      path: ""
    values:
      layout: default
      show_sidebar: true
      sidebar:
        - title: "Explore"
          items:
            - title: "My Projects"
              url: /projects
            - title: "Blog"
              url: /blog
            - title: "About Me"
              url: /about
        - title: "Connect"
          items:
            - icon: github
              url: https://github.com/oliverjacksonzht
            - icon: linkedin
              url: https://linkedin.com/in/YOUR_ID
